### ISSUE TITLE
请问几个问题大佬~

### ISSUE THREAD

**Issue by JavaHackSen** [zoudingyi/fish-touching-bot#3]
1、只支持可以登录web网页版的微信吗？
2、请问登录失败，是因为不支持登录web网页版导致的还是缺少配置呢？
![image](https://user-images.githubusercontent.com/37896126/150937595-a22f1c2b-0803-41c6-a3ac-aa31f948d86d.png)

**Comment by zoudingyi** [comment]
wechaty-puppet-wechat 协议不能用了导致的，跟前段时间微信更新了UOS登录有关。
